PREP_TIME: 5
PPH_OFFLOAD:
  LOOSE_TRAILER: 835
  LOOSE_VAN: 835
  CAGE: 540
  ULD: 549
  BAGGAGE_CART: 549
PPH_LOAD:
  LOOSE_TRAILER: 400
  LOOSE_VAN: 614
  CAGE: 540
  ULD: 665
  BAGGAGE_CART: 665
UNIT_CONVERTION:
  PIECE_PER_BAG: 27
  PARCEL_PER_CAGE_DG: 16
  PARCEL_PER_CAGE_NCY: 16
  HPC: 5
GROWTH_RATE: 0.03
MAX_BUFFER: 1500
OUTBOUND_BUFFER:
  LOOSE_TRAILER: 40
  LOOSE_VAN: 0
  CAGE: 0
  ULD: 0
